version: "3.2"

services:
  blue:
    image: ${REPO_URL}:blue
    deploy:
      replicas: 2
      labels:
        com.docker.lb.hosts: ${BLUE_HOSTNAME}
        com.docker.lb.port: 80
        com.docker.lb.network: testapp-network
        service-status: live
    networks:
      - testapp-network

  green:
    image: ${REPO_URL}:green
    deploy:
      replicas: 2
      labels:
        com.docker.lb.hosts: ${LIVE_HOSTNAME},${GREEN_HOSTNAME}
        com.docker.lb.port: 80
        com.docker.lb.network: testapp-network
        service-status: standby
    networks:
      - testapp-network

networks:
  testapp-network:
    driver: overlay
